server:
  port: 8080
  servlet:
    context-path: /

spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jaelog?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  output:
    ansi:
      enabled: always